/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Geocode
         * @description Resolve a free-text place query into candidate locations.
         */
        post: operations["geocode_geocode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Route
         * @description Plan a route between two points, respecting any avoidance constraints.
         */
        post: operations["create_route_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Routes
         * @description Generate candidate routes between two points and keep only those matching every criterion.
         */
        post: operations["search_routes_routes_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Areas Route
         * @description Find polygon area features near a point, independent of any route.
         */
        post: operations["search_areas_route_areas_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{route_id}/reroute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reroute
         * @description Recompute a prior route with additional avoidance constraints.
         */
        post: operations["reroute_routes__route_id__reroute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Routes
         * @description Compare two previously planned routes: which is shorter/faster and how much their paths overlap.
         */
        post: operations["compare_routes_routes_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{route_id}/arrival-estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Estimate Arrival
         * @description Estimate arrival time for a planned route given a departure time.
         *
         *     This is a time-of-day/day-of-week heuristic, not live traffic.
         */
        post: operations["estimate_arrival_routes__route_id__arrival_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/isochrone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Isochrone
         * @description Compute the area reachable from a point within a time budget, over the real road network.
         */
        post: operations["isochrone_isochrone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routing/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description Which regions, if any, have fast pre-compiled Valhalla routing on this deployment.
         */
        get: operations["get_coverage_routing_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List dataset summaries across all geometry kinds (points, tracks, polygons).
         */
        get: operations["list_datasets_geodata_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset
         * @description Retrieve a dataset including all of its features, whatever its geometry kind.
         */
        get: operations["get_dataset_geodata_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/{dataset_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Dataset
         * @description Download a dataset's features as a GeoJSON FeatureCollection.
         */
        get: operations["download_dataset_geodata_datasets__dataset_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/tracks/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Track
         * @description Upload a GeoJSON FeatureCollection of timestamped Point features as a new track.
         */
        post: operations["upload_track_geodata_datasets_tracks_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/tracks/{track_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match Track
         * @description Snap a track's raw GPS points onto the actual roads it drove.
         *
         *     Requires the Valhalla routing backend (VALHALLA__TILE_URI) — 501s otherwise.
         */
        post: operations["match_track_geodata_datasets_tracks__track_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/tracks/{dataset_id}/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Label Track Point
         * @description Update a track point's tags.
         */
        patch: operations["label_track_point_geodata_datasets_tracks__dataset_id__features__feature_id__patch"];
        trace?: never;
    };
    "/geodata/datasets/tracks/{dataset_id}/features/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Tag Track Points
         * @description Apply and/or remove tags across a set of a track's points.
         */
        post: operations["bulk_tag_track_points_geodata_datasets_tracks__dataset_id__features_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/points/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Tabular Points
         * @description Preview a CSV/Excel file's columns and a sample of rows before uploading it as a point dataset.
         */
        post: operations["preview_tabular_points_geodata_datasets_points_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/points/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Point Dataset
         * @description Upload a GeoJSON, CSV, or Excel file of categorized Point features as a new point dataset.
         *
         *     Categorize either by naming a property/column present on each feature (`type_field`,
         *     e.g. "type") or, for a uniform dataset, by passing a single `default_type`. CSV/Excel
         *     files have no inherent geometry, so `lat_field`/`lon_field` name the columns to read
         *     coordinates from; every other column is carried over as filterable `properties`.
         */
        post: operations["upload_point_dataset_geodata_datasets_points_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/points/{dataset_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Point Feature
         * @description Add a single feature to an existing point dataset.
         */
        post: operations["add_point_feature_geodata_datasets_points__dataset_id__features_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/points/{dataset_id}/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Label Point Feature
         * @description Update a point feature's category, name, and tags.
         */
        patch: operations["label_point_feature_geodata_datasets_points__dataset_id__features__feature_id__patch"];
        trace?: never;
    };
    "/geodata/datasets/points/{dataset_id}/features/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Tag Point Features
         * @description Apply and/or remove tags across a set of a point dataset's features.
         */
        post: operations["bulk_tag_point_features_geodata_datasets_points__dataset_id__features_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/polygons/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Polygon Dataset
         * @description Upload a GeoJSON FeatureCollection of categorized Polygon features as a new polygon dataset.
         */
        post: operations["upload_polygon_dataset_geodata_datasets_polygons_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/polygons/{dataset_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Polygon Feature
         * @description Add a single feature to an existing polygon dataset.
         */
        post: operations["add_polygon_feature_geodata_datasets_polygons__dataset_id__features_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/polygons/{dataset_id}/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Label Polygon Feature
         * @description Update a polygon feature's category, name, and tags.
         */
        patch: operations["label_polygon_feature_geodata_datasets_polygons__dataset_id__features__feature_id__patch"];
        trace?: never;
    };
    "/geodata/datasets/polygons/{dataset_id}/features/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Tag Polygon Features
         * @description Apply and/or remove tags across a set of a polygon dataset's features.
         */
        post: operations["bulk_tag_polygon_features_geodata_datasets_polygons__dataset_id__features_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Config
         * @description Whether the frontend can skip prompting for an API key up front, and the model picker's options.
         */
        get: operations["get_agent_config_agent_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Stream an agent turn as an AI SDK UI Message Stream.
         */
        post: operations["chat_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentConfig
         * @description Server-side agent configuration exposed to the frontend.
         */
        AgentConfig: {
            /**
             * Hasserverkey
             * @description Whether the server can run the agent without a client-supplied API key
             */
            hasServerKey: boolean;
            /**
             * Models
             * @description Selectable models for the chat model picker
             */
            models: components["schemas"]["ModelOption"][];
            /**
             * Defaultmodelid
             * @description The model_id used when a chat request omits one
             */
            defaultModelId: string;
        };
        /**
         * AreaMatch
         * @description A tagged OSM feature found by find_area_features/search_areas, or one a candidate route passes through.
         *
         *     Most categories (restaurants, bus stops, police stations, etc.) are mapped as single points in
         *     OSM; a smaller set (parks, lakes, malls, bases, etc.) are mapped as polygons and carry a real
         *     boundary. geometry reflects whichever OSM actually has — area_m2/exit_count are only meaningful,
         *     and only populated, for a polygon match, since a point has no area or boundary for a road to
         *     touch. A request that filters on min_area_m2/min_boundary_count naturally keeps only polygon
         *     matches, since point matches never satisfy either.
         */
        AreaMatch: {
            /** Name */
            name?: string | null;
            /**
             * Category
             * @description A PoiCategory value, or 'key=value' for a match found via raw_tags/through_raw_tags
             */
            category: components["schemas"]["PoiCategory"] | string;
            /** Geometry */
            geometry: components["schemas"]["Point"] | components["schemas"]["Polygon"];
            /**
             * Aream2
             * @description Set only when geometry is a Polygon/MultiPolygon
             */
            areaM2?: number | null;
            /**
             * Exitcount
             * @description Set only when geometry is a Polygon/MultiPolygon. Distinct points where the road/path network contacts the feature's outer boundary, per the search's way-type and boundary-contact filters — a heuristic proxy for entrances/exits, since OSM entrance tagging is too inconsistent to rely on directly.
             */
            exitCount?: number | null;
            /**
             * Osmtype
             * @description OSM element type: node, way, or relation
             */
            osmType?: string | null;
            /** Osmid */
            osmId?: number | null;
            /**
             * Rawtags
             * @description Every OSM tag on the element (name, operator, website, etc.)
             */
            rawTags?: {
                [key: string]: string;
            };
            /**
             * Url
             * @description Link to the raw element on openstreetmap.org
             */
            url?: string | null;
        };
        /**
         * AreaSearchRequest
         * @description Find OSM features of any category (restaurants, bus stops, police stations, parks, lakes, ...) within a scope, independent of any route.
         *
         *     Not just polygon "area" features — most categories are single points in OSM, and come back
         *     that way (see AreaMatch); a smaller set (parks, lakes, malls, bases, etc.) are polygons and
         *     come back with their real boundary, area_m2, and exit_count. Unlike RouteSearchCriteria's
         *     through_* fields (which check whether a *planned route* passes through a qualifying polygon
         *     feature — a much stricter, often-empty condition, since most routes go around a park rather
         *     than through it), this searches for every matching feature within the scope directly — e.g.
         *     "show me all parks within 5km of downtown with at least 2 trails running through them", "every
         *     police station in Cook County", or "restaurants and parks between Falls Church and Rosslyn".
         *     Scope is exactly one of: origin + radius_m (a radius around a point), boundary (everywhere
         *     within a polygon — a named place's administrative boundary from GeocodeResult.boundary, or a
         *     hand-drawn area), or origin + destination + corridor_m (a strip between two points, for
         *     "between A and B" — independent of any actual planned route). To narrow a prior result to only
         *     the ones with a real boundary meeting some condition (e.g. "just the ones a small road touches
         *     the edge of"), set min_boundary_count/way_types/boundary_contact — this only ever keeps polygon
         *     matches, since a point has no boundary to touch.
         */
        AreaSearchRequest: {
            /**
             * Categories
             * @description e.g. [gas_station, coffee] to search both in one request
             */
            categories?: components["schemas"]["PoiCategory"][];
            /**
             * Rawtags
             * @description Raw OSM key/value tags for categories not in PoiCategory, e.g. {key: 'leisure', value: 'park'} or {key: 'tourism', value: 'museum'}. You know common OSM tagging conventions — use them directly rather than refusing a search just because it isn't in the curated category list. Combine freely with categories in the same call.
             */
            rawTags?: components["schemas"]["OsmTag"][];
            /** @description Center point for a radius search, or one end of a between-two-points corridor */
            origin?: components["schemas"]["Point"] | null;
            /**
             * Radiusm
             * @description Search radius around origin; required for a radius search
             */
            radiusM?: number | null;
            /**
             * Boundary
             * @description Search everywhere within this polygon instead of a radius, e.g. a city/county boundary or a hand-drawn area
             */
            boundary?: components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | null;
            /** @description Other end of a between-two-points corridor search; set together with origin */
            destination?: components["schemas"]["Point"] | null;
            /**
             * Corridorm
             * @description Half-width of the corridor between origin and destination; required when destination is set
             */
            corridorM?: number | null;
            /**
             * Waytypes
             * @description OSM highway= tag values that count toward min_boundary_count, e.g. ['path', 'footway', 'track'] for trails/paths, or ['residential', 'service'] for small roads. Empty means every way type counts.
             */
            wayTypes?: string[];
            /**
             * @description Whether a way must cross through the feature's boundary, merely touch it (e.g. a road that dead-ends at a park's edge), or either, to count toward min_boundary_count.
             * @default crosses
             */
            boundaryContact: components["schemas"]["BoundaryContact"];
            /**
             * Minaream2
             * @description Minimum area of the matching feature
             */
            minAreaM2?: number | null;
            /**
             * Minboundarycount
             * @description Minimum exit_count (see way_types/boundary_contact) of the matching feature
             */
            minBoundaryCount?: number | null;
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /**
         * ArrivalEstimate
         * @description A congestion-adjusted arrival estimate for a route.
         *
         *     There's no live traffic feed here — this applies a static time-of-day/day-of-week
         *     heuristic to the route's free-flow duration. Treat it as a rough estimate, not a
         *     real-time prediction.
         */
        ArrivalEstimate: {
            /** Routeid */
            routeId: string;
            /**
             * Datedeparture
             * Format: date-time
             */
            dateDeparture: string;
            /**
             * Datearrival
             * Format: date-time
             */
            dateArrival: string;
            /**
             * Freeflowdurations
             * @description The route's duration with no congestion adjustment
             */
            freeFlowDurationS: number;
            /**
             * Estimateddurations
             * @description Duration after applying the time-of-day heuristic
             */
            estimatedDurationS: number;
            /** Congestionmultiplier */
            congestionMultiplier: number;
        };
        /**
         * ArrivalEstimateRequest
         * @description Estimate an arrival time for a previously planned route given a departure time.
         */
        ArrivalEstimateRequest: {
            /**
             * Datedeparture
             * Format: date-time
             */
            dateDeparture: string;
        };
        /**
         * AvoidancePreferences
         * @description Constraints applied when computing a route.
         *
         *     exclude_polygons covers both user-drawn avoid areas and "avoid this road"
         *     (a buffer drawn around the clicked road's geometry) with one mechanism.
         *     avoid_point_datasets is resolved into more exclude_polygons before routing (see
         *     analytics/avoidance.py) — it's the mechanism that makes 'avoid known camera locations'
         *     actually change the computed route, rather than just reporting how many are passed.
         */
        AvoidancePreferences: {
            /**
             * Avoidtolls
             * @default false
             */
            avoidTolls: boolean;
            /**
             * Avoidhighways
             * @default false
             */
            avoidHighways: boolean;
            /**
             * Avoidunpaved
             * @default false
             */
            avoidUnpaved: boolean;
            /**
             * Avoidferries
             * @default false
             */
            avoidFerries: boolean;
            /** Excludepolygons */
            excludePolygons?: components["schemas"]["Polygon"][];
            /** Avoidpointdatasets */
            avoidPointDatasets?: components["schemas"]["PointDatasetAvoidance"][];
        };
        /** Body_preview_tabular_points_geodata_datasets_points_preview_post */
        Body_preview_tabular_points_geodata_datasets_points_preview_post: {
            /** File */
            file: string;
        };
        /** Body_upload_point_dataset_geodata_datasets_points_upload_post */
        Body_upload_point_dataset_geodata_datasets_points_upload_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
            /** Type Field */
            type_field?: string | null;
            /** Default Type */
            default_type?: string | null;
            /** Lat Field */
            lat_field?: string | null;
            /** Lon Field */
            lon_field?: string | null;
        };
        /** Body_upload_polygon_dataset_geodata_datasets_polygons_upload_post */
        Body_upload_polygon_dataset_geodata_datasets_polygons_upload_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
            /** Type Field */
            type_field?: string | null;
            /** Default Type */
            default_type?: string | null;
        };
        /** Body_upload_track_geodata_datasets_tracks_upload_post */
        Body_upload_track_geodata_datasets_tracks_upload_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
        };
        /**
         * BoundaryContact
         * @description How a way must relate to an area feature's boundary to count as a match.
         *
         *     CROSSES passes through the interior (a path that continues on the other side).
         *     TOUCHES reaches the boundary without necessarily continuing through it (e.g. a
         *     road that dead-ends right at a park's edge). ANY counts either.
         * @enum {string}
         */
        BoundaryContact: "crosses" | "touches" | "any";
        /**
         * BulkTagRequest
         * @description Apply and/or remove tags across a set of features in one dataset.
         */
        BulkTagRequest: {
            /** Featureids */
            featureIds: string[];
            /** Addtags */
            addTags?: string[];
            /** Removetags */
            removeTags?: string[];
        };
        /**
         * ChatRequest
         * @description A new message sent to the agent.
         */
        ChatRequest: {
            /** Message */
            message: string;
            /** Sessionid */
            sessionId?: string | null;
            /**
             * Apikey
             * @description Overrides the server-configured LLM API key for this request
             */
            apiKey?: string | null;
            /**
             * Modelid
             * @description Selects a model from AgentConfig.models; falls back to the server default
             */
            modelId?: string | null;
        };
        /**
         * CoverageRegion
         * @description An area with fast, pre-compiled Valhalla tile coverage.
         *
         *     Hand-curated documentation (see scripts/describe_coverage_area.py), not a build
         *     manifest — an area's bounds don't need to track 1:1 with whatever PBFs are actually
         *     registered for the tile build at any given moment.
         */
        CoverageRegion: {
            /** Name */
            name: string;
            /**
             * Url
             * @description Where this area's extract was originally downloaded from
             */
            url?: string | null;
            /** @description Rectangular bounding box of the area's OSM extract */
            bounds: components["schemas"]["Polygon"];
            /**
             * Dateadded
             * Format: date-time
             */
            dateAdded: string;
        };
        /**
         * Dataset
         * @description Summary of a dataset of any geometry kind, for the unified browsing list.
         */
        Dataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            geometryKind: components["schemas"]["DatasetGeometryKind"];
            /**
             * Featurecount
             * @default 0
             */
            featureCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /**
             * Datestart
             * @description Track datasets only
             */
            dateStart?: string | null;
            /**
             * Dateend
             * @description Track datasets only
             */
            dateEnd?: string | null;
        };
        /**
         * DatasetGeometryKind
         * @description The geometry a dataset's features carry.
         * @enum {string}
         */
        DatasetGeometryKind: "point" | "track" | "polygon";
        /**
         * GeocodeRequest
         * @description A free-text place lookup.
         */
        GeocodeRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /**
         * GeocodeResult
         * @description A single geocoding match.
         *
         *     Nominatim's raw OSM identity and address detail to show underlying element rather
         *     than just a name and a pin.
         */
        GeocodeResult: {
            /** Displayname */
            displayName: string;
            geometry: components["schemas"]["Point"];
            /** Placetype */
            placeType?: string | null;
            /**
             * Osmtype
             * @description OSM element type: node, way, or relation
             */
            osmType?: string | null;
            /** Osmid */
            osmId?: number | null;
            /**
             * Osmclass
             * @description Nominatim's category/class field, e.g. 'amenity', 'shop'
             */
            osmClass?: string | null;
            /**
             * Address
             * @description Structured address components (house_number, road, city, state, etc.)
             */
            address?: {
                [key: string]: string;
            };
            /**
             * Boundary
             * @description The result's actual administrative/area boundary (a city, county, park, etc.), when Nominatim has one — None for a point-only result like an address or POI. Pass this as AreaSearchRequest.boundary to search everywhere within the place rather than a radius around its center point.
             */
            boundary?: components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Service liveness status.
         */
        HealthStatus: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * Isochrone
         * @description The reachable area from a point within a time budget, over the real road network.
         */
        Isochrone: {
            origin: components["schemas"]["Point"];
            /** Minutes */
            minutes: number;
            geometry: components["schemas"]["Polygon"];
            /**
             * Reachablenodecount
             * @description Number of road-network nodes within the time budget — a rough density signal
             */
            reachableNodeCount: number;
        };
        /**
         * IsochroneRequest
         * @description Request the reachable area from a point within a time budget.
         */
        IsochroneRequest: {
            origin: components["schemas"]["Point"];
            /** Minutes */
            minutes: number;
            /** @default drive */
            networkType: components["schemas"]["NetworkType"];
            avoid?: components["schemas"]["AvoidancePreferences"];
        };
        /**
         * LLMProvider
         * @description Which pydantic-ai model backend to build.
         * @enum {string}
         */
        LLMProvider: "anthropic" | "google" | "openai_compatible";
        /**
         * LabelFeatureRequest
         * @description Replace a point/polygon feature's category, name, and tags with the given values.
         *
         *     Every field is applied as-is (name=None clears the name) — send the feature's
         *     current values for anything you don't mean to change.
         */
        LabelFeatureRequest: {
            /** Category */
            category: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * LabelTrackPointRequest
         * @description Update a track point's tags (track points have no category/name).
         */
        LabelTrackPointRequest: {
            /** Tags */
            tags?: string[];
        };
        /**
         * LineString
         * @description LineString Model
         */
        LineString: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "LineString";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[];
        };
        /**
         * MapMatchResult
         * @description A track's raw GPS points snapped onto the actual roads it drove.
         *
         *     Requires the Valhalla routing backend (map matching over raw networkx/osmnx
         *     graphs isn't implemented) — see datastores/valhalla/repository.py.
         */
        MapMatchResult: {
            /** Trackid */
            trackId: string;
            geometry: components["schemas"]["LineString"];
            /** Distancem */
            distanceM: number;
            /** Durations */
            durationS: number;
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
        };
        /**
         * ModelOption
         * @description A selectable LLM shown in the frontend's model picker.
         */
        ModelOption: {
            /** Id */
            id: string;
            provider: components["schemas"]["LLMProvider"];
            /** Label */
            label: string;
            /**
             * Haskey
             * @description Whether the server can authenticate this model without a client-supplied key
             */
            hasKey: boolean;
        };
        /**
         * MultiPolygon
         * @description MultiPolygon Model
         */
        MultiPolygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "MultiPolygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][][];
        };
        /**
         * NetworkType
         * @description osmnx street network filter — what mode of travel the road graph should represent.
         * @enum {string}
         */
        NetworkType: "drive" | "drive_service" | "walk" | "bike" | "all";
        /**
         * OsmTag
         * @description A raw OSM key/value tag pair, for POI categories outside the curated list.
         *
         *     e.g. key="leisure", value="dog_park" or key="tourism", value="museum".
         */
        OsmTag: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /**
         * PaginatedDatasetsResponse
         * @description Paginated list of dataset summaries across all geometry kinds.
         */
        PaginatedDatasetsResponse: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Totalpages */
            totalPages: number;
            /** Data */
            data: components["schemas"]["Dataset"][];
        };
        /**
         * PoiCategory
         * @description Curated, well-known POI categories with dedicated frontend icons.
         *
         *     Not exhaustive — OSM has hundreds of amenity/shop/leisure/tourism tags. For
         *     anything not listed here, pass raw_tags on the request instead of waiting
         *     for it to be added to this enum.
         * @enum {string}
         */
        PoiCategory: "gas_station" | "ev_charging" | "supermarket" | "restaurant" | "coffee" | "parking" | "rest_area" | "hotel" | "pharmacy" | "hospital" | "gym" | "park" | "bank" | "atm" | "car_repair" | "campground";
        /**
         * Point
         * @description Point Model
         */
        Point: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Point";
            /** Coordinates */
            coordinates: components["schemas"]["Position2D"] | components["schemas"]["Position3D"];
        };
        /**
         * PointDataset
         * @description Point dataset metadata, without its features.
         */
        PointDataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default point
             * @constant
             */
            geometryKind: "point";
            /**
             * Pointcount
             * @default 0
             */
            pointCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
        };
        /**
         * PointDatasetAvoidance
         * @description An uploaded point dataset's matching features to route around, e.g. known camera locations.
         *
         *     Resolved before routing by buffering every matching feature by buffer_m into an exclusion
         *     zone (the same mechanism as a user-drawn avoid area) — this is what makes 'avoid cameras'
         *     actually change the computed route, rather than just reporting how many are passed.
         */
        PointDatasetAvoidance: {
            /** Datasetid */
            datasetId: string;
            /**
             * Category
             * @description Filter to one category, e.g. 'camera'
             */
            category?: string | null;
            /**
             * Includetags
             * @description Only avoid features carrying at least one of these tags
             */
            includeTags?: string[];
            /**
             * Excludetags
             * @description Never avoid features carrying any of these tags, e.g. ['indoor'] for cameras with no bearing on a road route
             */
            excludeTags?: string[];
            /**
             * Corridorm
             * @description How far off the route/straight origin-destination line a feature still counts as relevant
             * @default 1000
             */
            corridorM: number;
            /**
             * Bufferm
             * @description Radius around each matching feature excluded from routing
             * @default 50
             */
            bufferM: number;
        };
        /**
         * PointDatasetDetail
         * @description A point dataset including its full set of features.
         */
        PointDatasetDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default point
             * @constant
             */
            geometryKind: "point";
            /**
             * Pointcount
             * @default 0
             */
            pointCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /** Points */
            points?: components["schemas"]["PointFeature"][];
        };
        /**
         * PointFeature
         * @description A persisted point dataset feature.
         */
        PointFeature: {
            geometry: components["schemas"]["Point"];
            /** Category */
            category: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Properties
             * @description Arbitrary extra columns/properties carried over from the uploaded file
             */
            properties?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Datasetid */
            datasetId: string;
        };
        /**
         * PointFeatureCreate
         * @description A single categorized point to add to a point dataset.
         */
        PointFeatureCreate: {
            geometry: components["schemas"]["Point"];
            /** Category */
            category: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Properties
             * @description Arbitrary extra columns/properties carried over from the uploaded file
             */
            properties?: {
                [key: string]: unknown;
            };
        };
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        /**
         * PolygonDataset
         * @description Polygon dataset metadata, without its features.
         */
        PolygonDataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default polygon
             * @constant
             */
            geometryKind: "polygon";
            /**
             * Polygoncount
             * @default 0
             */
            polygonCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
        };
        /**
         * PolygonDatasetDetail
         * @description A polygon dataset including its full set of features.
         */
        PolygonDatasetDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default polygon
             * @constant
             */
            geometryKind: "polygon";
            /**
             * Polygoncount
             * @default 0
             */
            polygonCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /** Polygons */
            polygons?: components["schemas"]["PolygonFeature"][];
        };
        /**
         * PolygonFeature
         * @description A persisted polygon dataset feature.
         */
        PolygonFeature: {
            geometry: components["schemas"]["Polygon"];
            /** Category */
            category: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /** Datasetid */
            datasetId: string;
        };
        /**
         * PolygonFeatureCreate
         * @description A single categorized polygon to add to a polygon dataset.
         */
        PolygonFeatureCreate: {
            geometry: components["schemas"]["Polygon"];
            /** Category */
            category: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[];
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /**
         * RerouteRequest
         * @description A request to recompute a prior route, optionally with a new ordered stop list.
         */
        RerouteRequest: {
            avoid: components["schemas"]["AvoidancePreferences"];
            /**
             * Avoidpriorroute
             * @description Exclude the previously computed route's own path, for 'take a different way'
             * @default false
             */
            avoidPriorRoute: boolean;
            /**
             * Waypoints
             * @description Full replacement ordered list of intermediate stops. Omit to keep the prior route's waypoints unchanged; pass the prior list plus/minus a stop, in the desired order, to add or remove one (e.g. 'add a stop at the gas station').
             */
            waypoints?: components["schemas"]["Point"][] | null;
        };
        /**
         * Route
         * @description A computed route.
         */
        Route: {
            /** Id */
            id: string;
            geometry: components["schemas"]["LineString"];
            /** Distancem */
            distanceM: number;
            /** Durations */
            durationS: number;
            origin: components["schemas"]["Point"];
            destination: components["schemas"]["Point"];
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][];
            /** @default drive */
            networkType: components["schemas"]["NetworkType"];
            avoid: components["schemas"]["AvoidancePreferences"];
            /**
             * Legs
             * @description Per-stop segments; >1 entry when waypoints are set
             */
            legs?: components["schemas"]["RouteLeg"][];
            /** Alternates */
            alternates?: components["schemas"]["RouteAlternate"][];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
        };
        /**
         * RouteAlternate
         * @description A less-preferred path between the same origin and destination as a computed route.
         */
        RouteAlternate: {
            /** Id */
            id: string;
            geometry: components["schemas"]["LineString"];
            /** Distancem */
            distanceM: number;
            /** Durations */
            durationS: number;
        };
        /**
         * RouteCompareRequest
         * @description Two previously computed routes to compare.
         */
        RouteCompareRequest: {
            /** Routeida */
            routeIdA: string;
            /** Routeidb */
            routeIdB: string;
        };
        /**
         * RouteComparison
         * @description A comparison between two previously computed routes.
         */
        RouteComparison: {
            /** Routeaid */
            routeAId: string;
            /** Routebid */
            routeBId: string;
            /**
             * Distancedeltam
             * @description route_b's distance minus route_a's; negative means b is shorter
             */
            distanceDeltaM: number;
            /**
             * Durationdeltas
             * @description route_b's duration minus route_a's; negative means b is faster
             */
            durationDeltaS: number;
            /**
             * Sharedpathfraction
             * @description Fraction of the two routes' combined length that follows the same path (within ~30m)
             */
            sharedPathFraction: number;
        };
        /**
         * RouteLeg
         * @description One point-to-point segment of a route, between consecutive origin/waypoint/destination stops.
         */
        RouteLeg: {
            origin: components["schemas"]["Point"];
            destination: components["schemas"]["Point"];
            geometry: components["schemas"]["LineString"];
            /** Distancem */
            distanceM: number;
            /** Durations */
            durationS: number;
        };
        /**
         * RouteRequest
         * @description A request to plan a route between two points, optionally via ordered intermediate stops.
         */
        RouteRequest: {
            origin: components["schemas"]["Point"];
            destination: components["schemas"]["Point"];
            /**
             * Waypoints
             * @description Ordered intermediate stops between origin and destination
             */
            waypoints?: components["schemas"]["Point"][];
            /** @default drive */
            networkType: components["schemas"]["NetworkType"];
            avoid?: components["schemas"]["AvoidancePreferences"];
            /**
             * Maxalternates
             * @description Additional alternative paths to compute alongside the primary route (Valhalla backend only). Only honored when waypoints is empty — Valhalla doesn't support alternates for multi-stop trips, so this is silently ignored if waypoints are set.
             * @default 0
             */
            maxAlternates: number;
        };
        /**
         * RouteSearchCriteria
         * @description Criteria for generating and filtering candidate routes, rather than planning one specific route.
         *
         *     Mode and avoidance map directly onto routing-engine inputs. The through_* area criteria can't
         *     be expressed to the routing engine at all, so every generated candidate is checked against them
         *     after the fact, and only candidates clearing every requested threshold are returned.
         */
        RouteSearchCriteria: {
            origin: components["schemas"]["Point"];
            destination: components["schemas"]["Point"];
            /** @default drive */
            networkType: components["schemas"]["NetworkType"];
            avoid?: components["schemas"]["AvoidancePreferences"];
            /**
             * Avoidplaces
             * @description Free-text places or roads to avoid, e.g. 'I-95' or 'downtown' — geocoded and excluded with a buffer of avoid_radius_m, combined with any structured avoid preferences.
             */
            avoidPlaces?: string[];
            /**
             * Avoidradiusm
             * @default 300
             */
            avoidRadiusM: number;
            /**
             * Throughcategories
             * @description e.g. [park] to require the route pass through a park; combine freely with through_raw_tags
             */
            throughCategories?: components["schemas"]["PoiCategory"][];
            /**
             * Throughrawtags
             * @description Raw OSM key/value tags for an area feature not in PoiCategory, e.g. {key: 'natural', value: 'water'} for a lake or {key: 'shop', value: 'mall'}. Use common OSM tagging conventions directly rather than refusing a search just because it isn't in the curated category list.
             */
            throughRawTags?: components["schemas"]["OsmTag"][];
            /**
             * Minaream2
             * @description Minimum area of the through_categories/through_raw_tags feature
             */
            minAreaM2?: number | null;
            /**
             * Minareaexits
             * @description Minimum exit_count of the through_categories/through_raw_tags feature
             */
            minAreaExits?: number | null;
            /**
             * Throughwaytypes
             * @description OSM highway= tag values that count toward min_area_exits, e.g. ['path', 'footway', 'track'] for trails/paths, or ['residential', 'service'] for small roads. Empty means every way type counts. Use common OSM tagging conventions directly, same as through_raw_tags.
             */
            throughWayTypes?: string[];
            /**
             * @description Whether a way must cross through the feature's boundary, merely touch it (e.g. a road that dead-ends at a park's edge), or either, to count toward min_area_exits.
             * @default crosses
             */
            throughBoundaryContact: components["schemas"]["BoundaryContact"];
            /**
             * Areacorridorm
             * @description How close the route must pass to the area feature to count as going through it
             * @default 50
             */
            areaCorridorM: number;
            /**
             * Maxcandidates
             * @description Alternative paths to consider beyond the primary route (Valhalla backend only — the networkx fallback only ever produces the primary route).
             * @default 3
             */
            maxCandidates: number;
        };
        /**
         * RouteSearchMatch
         * @description One candidate route that satisfied every criterion in a RouteSearchCriteria search.
         */
        RouteSearchMatch: {
            route: components["schemas"]["Route"];
            /** @description The qualifying area feature the route passes through, when area criteria were set */
            matchedArea?: components["schemas"]["AreaMatch"] | null;
        };
        /**
         * RoutingCoverage
         * @description Which regions, if any, have fast pre-compiled routing on this deployment.
         *
         *     backend='networkx' means every request is routed live over a fetched OSM graph —
         *     slower everywhere, but with no notion of compiled regions, so regions is always empty.
         *     backend='valhalla' means routing is fast and in-process, but only within regions —
         *     a request outside every listed region will fail outright (see is_within_coverage).
         */
        RoutingCoverage: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "valhalla" | "networkx";
            /** Regions */
            regions?: components["schemas"]["CoverageRegion"][];
        };
        /**
         * TabularPreview
         * @description A preview of an uploaded CSV/Excel file's columns, used to map lat/long/category fields before upload.
         */
        TabularPreview: {
            /** Columns */
            columns: string[];
            /** Samplerows */
            sampleRows?: {
                [key: string]: unknown;
            }[];
            /** Rowcount */
            rowCount: number;
        };
        /**
         * Track
         * @description Track metadata, without its points.
         */
        Track: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default track
             * @constant
             */
            geometryKind: "track";
            source: components["schemas"]["TrackSource"];
            /**
             * Pointcount
             * @default 0
             */
            pointCount: number;
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /** Datestart */
            dateStart?: string | null;
            /** Dateend */
            dateEnd?: string | null;
        };
        /**
         * TrackDetail
         * @description A track including its full set of points.
         */
        TrackDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default track
             * @constant
             */
            geometryKind: "track";
            source: components["schemas"]["TrackSource"];
            /**
             * Pointcount
             * @default 0
             */
            pointCount: number;
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /** Datestart */
            dateStart?: string | null;
            /** Dateend */
            dateEnd?: string | null;
            /** Points */
            points?: components["schemas"]["TrackPoint"][];
        };
        /**
         * TrackPoint
         * @description A persisted track point.
         */
        TrackPoint: {
            geometry: components["schemas"]["Point"];
            /**
             * Daterecorded
             * Format: date-time
             */
            dateRecorded: string;
            /** Elevationm */
            elevationM?: number | null;
            /** Speedmps */
            speedMps?: number | null;
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /** Trackid */
            trackId: string;
        };
        /**
         * TrackSource
         * @description Origin format of an uploaded track.
         * @enum {string}
         */
        TrackSource: "geojson" | "gpx" | "synthetic";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    geocode_geocode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_route_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_routes_routes_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteSearchCriteria"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSearchMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_areas_route_areas_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reroute_routes__route_id__reroute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_routes_routes_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteCompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_arrival_routes__route_id__arrival_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArrivalEstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArrivalEstimate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    isochrone_isochrone_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IsochroneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Isochrone"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_routing_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingCoverage"];
                };
            };
        };
    };
    list_datasets_geodata_datasets_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                geometry_kind?: components["schemas"]["DatasetGeometryKind"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDatasetsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_geodata_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointDatasetDetail"] | components["schemas"]["TrackDetail"] | components["schemas"]["PolygonDatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_dataset_geodata_datasets__dataset_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_track_geodata_datasets_tracks_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_track_geodata_datasets_tracks_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_track_geodata_datasets_tracks__track_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapMatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_track_point_geodata_datasets_tracks__dataset_id__features__feature_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelTrackPointRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPoint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_tag_track_points_geodata_datasets_tracks__dataset_id__features_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_tabular_points_geodata_datasets_points_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_tabular_points_geodata_datasets_points_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TabularPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_point_dataset_geodata_datasets_points_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_point_dataset_geodata_datasets_points_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointDataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_point_feature_geodata_datasets_points__dataset_id__features_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointFeatureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_point_feature_geodata_datasets_points__dataset_id__features__feature_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelFeatureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_tag_point_features_geodata_datasets_points__dataset_id__features_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointFeature"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_polygon_dataset_geodata_datasets_polygons_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_polygon_dataset_geodata_datasets_polygons_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolygonDataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_polygon_feature_geodata_datasets_polygons__dataset_id__features_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolygonFeatureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolygonFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_polygon_feature_geodata_datasets_polygons__dataset_id__features__feature_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelFeatureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolygonFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_tag_polygon_features_geodata_datasets_polygons__dataset_id__features_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolygonFeature"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_config_agent_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfig"];
                };
            };
        };
    };
    chat_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
