/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Geocode
         * @description Resolve a free-text place query into candidate locations.
         */
        post: operations["geocode_geocode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Route
         * @description Plan a route between two points, respecting any avoidance constraints.
         */
        post: operations["create_route_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{route_id}/reroute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reroute
         * @description Recompute a prior route with additional avoidance constraints.
         */
        post: operations["reroute_routes__route_id__reroute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List dataset summaries across all geometry kinds (points, tracks, polygons).
         */
        get: operations["list_datasets_geodata_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset
         * @description Retrieve a dataset including all of its features, whatever its geometry kind.
         */
        get: operations["get_dataset_geodata_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/{dataset_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Dataset
         * @description Download a dataset's features as a GeoJSON FeatureCollection.
         */
        get: operations["download_dataset_geodata_datasets__dataset_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/tracks/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Track
         * @description Upload a GeoJSON FeatureCollection of timestamped Point features as a new track.
         */
        post: operations["upload_track_geodata_datasets_tracks_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/tracks/{track_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match Track
         * @description Snap a track's raw GPS points onto the actual roads it drove.
         *
         *     Requires the Valhalla routing backend (VALHALLA__TILE_URI) — 501s otherwise.
         */
        post: operations["match_track_geodata_datasets_tracks__track_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/tracks/{dataset_id}/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Label Track Point
         * @description Update a track point's tags.
         */
        patch: operations["label_track_point_geodata_datasets_tracks__dataset_id__features__feature_id__patch"];
        trace?: never;
    };
    "/geodata/datasets/tracks/{dataset_id}/features/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Tag Track Points
         * @description Apply and/or remove tags across a set of a track's points.
         */
        post: operations["bulk_tag_track_points_geodata_datasets_tracks__dataset_id__features_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/points/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Point Dataset
         * @description Upload a GeoJSON FeatureCollection of categorized Point features as a new point dataset.
         *
         *     Categorize either by naming a property present on each feature (`type_field`,
         *     e.g. "type") or, for a uniform dataset, by passing a single `default_type`.
         */
        post: operations["upload_point_dataset_geodata_datasets_points_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/points/{dataset_id}/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Label Point Feature
         * @description Update a point feature's category, name, and tags.
         */
        patch: operations["label_point_feature_geodata_datasets_points__dataset_id__features__feature_id__patch"];
        trace?: never;
    };
    "/geodata/datasets/points/{dataset_id}/features/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Tag Point Features
         * @description Apply and/or remove tags across a set of a point dataset's features.
         */
        post: operations["bulk_tag_point_features_geodata_datasets_points__dataset_id__features_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/polygons/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Polygon Dataset
         * @description Upload a GeoJSON FeatureCollection of categorized Polygon features as a new polygon dataset.
         */
        post: operations["upload_polygon_dataset_geodata_datasets_polygons_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geodata/datasets/polygons/{dataset_id}/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Label Polygon Feature
         * @description Update a polygon feature's category, name, and tags.
         */
        patch: operations["label_polygon_feature_geodata_datasets_polygons__dataset_id__features__feature_id__patch"];
        trace?: never;
    };
    "/geodata/datasets/polygons/{dataset_id}/features/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Tag Polygon Features
         * @description Apply and/or remove tags across a set of a polygon dataset's features.
         */
        post: operations["bulk_tag_polygon_features_geodata_datasets_polygons__dataset_id__features_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Config
         * @description Whether the frontend can skip prompting for an API key up front.
         */
        get: operations["get_agent_config_agent_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Stream an agent turn as an AI SDK UI Message Stream.
         */
        post: operations["chat_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentConfig
         * @description Server-side agent configuration exposed to the frontend.
         */
        AgentConfig: {
            /**
             * Hasserverkey
             * @description Whether the server can run the agent without a client-supplied API key
             */
            hasServerKey: boolean;
        };
        /**
         * AvoidancePreferences
         * @description Constraints applied when computing a route.
         *
         *     exclude_polygons covers both user-drawn avoid areas and "avoid this road"
         *     (a buffer drawn around the clicked road's geometry) with one mechanism.
         */
        AvoidancePreferences: {
            /**
             * Avoidtolls
             * @default false
             */
            avoidTolls: boolean;
            /**
             * Avoidhighways
             * @default false
             */
            avoidHighways: boolean;
            /**
             * Avoidunpaved
             * @default false
             */
            avoidUnpaved: boolean;
            /**
             * Avoidferries
             * @default false
             */
            avoidFerries: boolean;
            /** Excludepolygons */
            excludePolygons?: components["schemas"]["Polygon"][];
        };
        /** Body_upload_point_dataset_geodata_datasets_points_upload_post */
        Body_upload_point_dataset_geodata_datasets_points_upload_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
            /** Type Field */
            type_field?: string | null;
            /** Default Type */
            default_type?: string | null;
        };
        /** Body_upload_polygon_dataset_geodata_datasets_polygons_upload_post */
        Body_upload_polygon_dataset_geodata_datasets_polygons_upload_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
            /** Type Field */
            type_field?: string | null;
            /** Default Type */
            default_type?: string | null;
        };
        /** Body_upload_track_geodata_datasets_tracks_upload_post */
        Body_upload_track_geodata_datasets_tracks_upload_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
        };
        /**
         * BulkTagRequest
         * @description Apply and/or remove tags across a set of features in one dataset.
         */
        BulkTagRequest: {
            /** Featureids */
            featureIds: string[];
            /** Addtags */
            addTags?: string[];
            /** Removetags */
            removeTags?: string[];
        };
        /**
         * ChatRequest
         * @description A new message sent to the agent.
         */
        ChatRequest: {
            /** Message */
            message: string;
            /** Sessionid */
            sessionId?: string | null;
            /**
             * Apikey
             * @description Overrides the server-configured LLM API key for this request
             */
            apiKey?: string | null;
        };
        /**
         * Dataset
         * @description Summary of a dataset of any geometry kind, for the unified browsing list.
         */
        Dataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            geometryKind: components["schemas"]["DatasetGeometryKind"];
            /**
             * Featurecount
             * @default 0
             */
            featureCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /**
             * Datestart
             * @description Track datasets only
             */
            dateStart?: string | null;
            /**
             * Dateend
             * @description Track datasets only
             */
            dateEnd?: string | null;
        };
        /**
         * DatasetGeometryKind
         * @description The geometry a dataset's features carry.
         * @enum {string}
         */
        DatasetGeometryKind: "point" | "track" | "polygon";
        /**
         * GeocodeRequest
         * @description A free-text place lookup.
         */
        GeocodeRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /**
         * GeocodeResult
         * @description A single geocoding match.
         */
        GeocodeResult: {
            /** Displayname */
            displayName: string;
            geometry: components["schemas"]["Point"];
            /** Placetype */
            placeType?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Service liveness status.
         */
        HealthStatus: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * LabelFeatureRequest
         * @description Replace a point/polygon feature's category, name, and tags with the given values.
         *
         *     Every field is applied as-is (name=None clears the name) — send the feature's
         *     current values for anything you don't mean to change.
         */
        LabelFeatureRequest: {
            /** Category */
            category: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * LabelTrackPointRequest
         * @description Update a track point's tags (track points have no category/name).
         */
        LabelTrackPointRequest: {
            /** Tags */
            tags?: string[];
        };
        /**
         * LineString
         * @description LineString Model
         */
        LineString: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "LineString";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[];
        };
        /**
         * MapMatchResult
         * @description A track's raw GPS points snapped onto the actual roads it drove.
         *
         *     Requires the Valhalla routing backend (map matching over raw networkx/osmnx
         *     graphs isn't implemented) — see datastores/valhalla/repository.py.
         */
        MapMatchResult: {
            /** Trackid */
            trackId: string;
            geometry: components["schemas"]["LineString"];
            /** Distancem */
            distanceM: number;
            /** Durations */
            durationS: number;
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
        };
        /**
         * NetworkType
         * @description osmnx street network filter — what mode of travel the road graph should represent.
         * @enum {string}
         */
        NetworkType: "drive" | "drive_service" | "walk" | "bike" | "all";
        /**
         * PaginatedDatasetsResponse
         * @description Paginated list of dataset summaries across all geometry kinds.
         */
        PaginatedDatasetsResponse: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Totalpages */
            totalPages: number;
            /** Data */
            data: components["schemas"]["Dataset"][];
        };
        /**
         * Point
         * @description Point Model
         */
        Point: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Point";
            /** Coordinates */
            coordinates: components["schemas"]["Position2D"] | components["schemas"]["Position3D"];
        };
        /**
         * PointDataset
         * @description Point dataset metadata, without its features.
         */
        PointDataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default point
             * @constant
             */
            geometryKind: "point";
            /**
             * Pointcount
             * @default 0
             */
            pointCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
        };
        /**
         * PointDatasetDetail
         * @description A point dataset including its full set of features.
         */
        PointDatasetDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default point
             * @constant
             */
            geometryKind: "point";
            /**
             * Pointcount
             * @default 0
             */
            pointCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /** Points */
            points?: components["schemas"]["PointFeature"][];
        };
        /**
         * PointFeature
         * @description A persisted point dataset feature.
         */
        PointFeature: {
            geometry: components["schemas"]["Point"];
            /** Category */
            category: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /** Datasetid */
            datasetId: string;
        };
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        /**
         * PolygonDataset
         * @description Polygon dataset metadata, without its features.
         */
        PolygonDataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default polygon
             * @constant
             */
            geometryKind: "polygon";
            /**
             * Polygoncount
             * @default 0
             */
            polygonCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
        };
        /**
         * PolygonDatasetDetail
         * @description A polygon dataset including its full set of features.
         */
        PolygonDatasetDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default polygon
             * @constant
             */
            geometryKind: "polygon";
            /**
             * Polygoncount
             * @default 0
             */
            polygonCount: number;
            /** Categories */
            categories?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /** Polygons */
            polygons?: components["schemas"]["PolygonFeature"][];
        };
        /**
         * PolygonFeature
         * @description A persisted polygon dataset feature.
         */
        PolygonFeature: {
            geometry: components["schemas"]["Polygon"];
            /** Category */
            category: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /** Datasetid */
            datasetId: string;
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /**
         * RerouteRequest
         * @description A request to recompute a prior route, optionally with a new ordered stop list.
         */
        RerouteRequest: {
            avoid: components["schemas"]["AvoidancePreferences"];
            /**
             * Avoidpriorroute
             * @description Exclude the previously computed route's own path, for 'take a different way'
             * @default false
             */
            avoidPriorRoute: boolean;
            /**
             * Waypoints
             * @description Full replacement ordered list of intermediate stops. Omit to keep the prior route's waypoints unchanged; pass the prior list plus/minus a stop, in the desired order, to add or remove one (e.g. 'add a stop at the gas station').
             */
            waypoints?: components["schemas"]["Point"][] | null;
        };
        /**
         * Route
         * @description A computed route.
         */
        Route: {
            /** Id */
            id: string;
            geometry: components["schemas"]["LineString"];
            /** Distancem */
            distanceM: number;
            /** Durations */
            durationS: number;
            origin: components["schemas"]["Point"];
            destination: components["schemas"]["Point"];
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][];
            /** @default drive */
            networkType: components["schemas"]["NetworkType"];
            avoid: components["schemas"]["AvoidancePreferences"];
            /**
             * Legs
             * @description Per-stop segments; >1 entry when waypoints are set
             */
            legs?: components["schemas"]["RouteLeg"][];
            /** Alternates */
            alternates?: components["schemas"]["RouteAlternate"][];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
        };
        /**
         * RouteAlternate
         * @description A less-preferred path between the same origin and destination as a computed route.
         */
        RouteAlternate: {
            /** Id */
            id: string;
            geometry: components["schemas"]["LineString"];
            /** Distancem */
            distanceM: number;
            /** Durations */
            durationS: number;
        };
        /**
         * RouteLeg
         * @description One point-to-point segment of a route, between consecutive origin/waypoint/destination stops.
         */
        RouteLeg: {
            origin: components["schemas"]["Point"];
            destination: components["schemas"]["Point"];
            geometry: components["schemas"]["LineString"];
            /** Distancem */
            distanceM: number;
            /** Durations */
            durationS: number;
        };
        /**
         * RouteRequest
         * @description A request to plan a route between two points, optionally via ordered intermediate stops.
         */
        RouteRequest: {
            origin: components["schemas"]["Point"];
            destination: components["schemas"]["Point"];
            /**
             * Waypoints
             * @description Ordered intermediate stops between origin and destination
             */
            waypoints?: components["schemas"]["Point"][];
            /** @default drive */
            networkType: components["schemas"]["NetworkType"];
            avoid?: components["schemas"]["AvoidancePreferences"];
            /**
             * Maxalternates
             * @description Additional alternative paths to compute alongside the primary route (Valhalla backend only). Only honored when waypoints is empty — Valhalla doesn't support alternates for multi-stop trips, so this is silently ignored if waypoints are set.
             * @default 0
             */
            maxAlternates: number;
        };
        /**
         * Track
         * @description Track metadata, without its points.
         */
        Track: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default track
             * @constant
             */
            geometryKind: "track";
            source: components["schemas"]["TrackSource"];
            /**
             * Pointcount
             * @default 0
             */
            pointCount: number;
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /** Datestart */
            dateStart?: string | null;
            /** Dateend */
            dateEnd?: string | null;
        };
        /**
         * TrackDetail
         * @description A track including its full set of points.
         */
        TrackDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Geometrykind
             * @default track
             * @constant
             */
            geometryKind: "track";
            source: components["schemas"]["TrackSource"];
            /**
             * Pointcount
             * @default 0
             */
            pointCount: number;
            /** Tags */
            tags?: string[];
            /**
             * Datecreated
             * Format: date-time
             */
            dateCreated: string;
            /** Datestart */
            dateStart?: string | null;
            /** Dateend */
            dateEnd?: string | null;
            /** Points */
            points?: components["schemas"]["TrackPoint"][];
        };
        /**
         * TrackPoint
         * @description A persisted track point.
         */
        TrackPoint: {
            geometry: components["schemas"]["Point"];
            /**
             * Daterecorded
             * Format: date-time
             */
            dateRecorded: string;
            /** Elevationm */
            elevationM?: number | null;
            /** Speedmps */
            speedMps?: number | null;
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /** Trackid */
            trackId: string;
        };
        /**
         * TrackSource
         * @description Origin format of an uploaded track.
         * @enum {string}
         */
        TrackSource: "geojson" | "gpx" | "synthetic";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    geocode_geocode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_route_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reroute_routes__route_id__reroute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_geodata_datasets_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                geometry_kind?: components["schemas"]["DatasetGeometryKind"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDatasetsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_geodata_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointDatasetDetail"] | components["schemas"]["TrackDetail"] | components["schemas"]["PolygonDatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_dataset_geodata_datasets__dataset_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_track_geodata_datasets_tracks_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_track_geodata_datasets_tracks_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_track_geodata_datasets_tracks__track_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapMatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_track_point_geodata_datasets_tracks__dataset_id__features__feature_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelTrackPointRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPoint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_tag_track_points_geodata_datasets_tracks__dataset_id__features_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_point_dataset_geodata_datasets_points_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_point_dataset_geodata_datasets_points_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointDataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_point_feature_geodata_datasets_points__dataset_id__features__feature_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelFeatureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_tag_point_features_geodata_datasets_points__dataset_id__features_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointFeature"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_polygon_dataset_geodata_datasets_polygons_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_polygon_dataset_geodata_datasets_polygons_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolygonDataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_polygon_feature_geodata_datasets_polygons__dataset_id__features__feature_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelFeatureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolygonFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_tag_polygon_features_geodata_datasets_polygons__dataset_id__features_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolygonFeature"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_config_agent_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfig"];
                };
            };
        };
    };
    chat_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
